name: Timetracker Service

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  timetracker-service-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: mvn clean
      - run: mvn install
      - run: mvn -DskipTests=true spring-boot:build-image -Dspring-boot.build-image.imageName=dbruns91/native-demo:${{ github.run_attempt }}-SNAPSHOT
      - run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker push dbruns91/native-demo:${{ github.run_attempt }}-SNAPSHOT
